### ISSUE TITLE
How to load the pretrained model and use it for prediction ?

### ISSUE THREAD

**Issue by PrithivirajDamodaran** [vishwapardeshi/Custom_NER_Recipe_Ingredient_Parser#15]
Hi I tried loading the ner_model.pkl in the models folder but it's not loading. Can you advice ?

**Comment by amitness** [comment]
You need to use `spacy==2.3.2` and joblib to load the pickled file. 
https://colab.research.google.com/drive/15u8_PYERKDdKOovGKwGomu51qM77qG5U?usp=sharing

**Comment by PrithivirajDamodaran** [comment]
Thank you ! , but I trained my own :)
